name = "grimes-stock-check"
main = "index.js"
compatibility_date = "2026-10-01"
workers_dev = true

# Shared stock answers (STOCK) and uploaded logos (FILES).
[[kv_namespaces]]
binding = "STOCK"
id = "1da45a1b762c431488115e3ff137964c"

[[kv_namespaces]]
binding = "FILES"
id = "c6a5883fc6d141c9bb0819435891621a"
